apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edgeproxy-role
rules:
  - apiGroups: [""]
    resources:
      - pods
      - nodes
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: edge-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edgeproxy-role
subjects:
  - kind: ServiceAccount
    name: edgeproxy-sa
    namespace: proxima-scheduler