apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: edgeproxy
  namespace: proxima-scheduler
  labels:
    app: edgeproxy
spec:
  selector:
    matchLabels:
      app: edgeproxy
  template:
    metadata:
      labels:
        app: edgeproxy
    spec:
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "edge"
        effect: "NoSchedule"
      nodeSelector:
        edge: "true"
      containers:
      - name: edgeproxy
        image: bogdanb0gdan/proxima-scheduler:latest
        command: ["/edgeproxy"]
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "250m"
            memory: "128Mi"
        ports:
          - containerPort: 8080
        env:
        - name: DATABASE_ENABLED
          value: "true"
        - name: INFLUXDB_ADDRESS
          value: "http://172.19.0.7:8086"
        - name: INFLUXDB_TOKEN
          valueFrom:
            secretKeyRef:
              name: influxdb-auth-token
              key: INFLUXDB_TOKEN
        # used on Kind cluster locally,
        # the ip of the Node, needed for edgeproxy + pinger
        #- name: KIND_NETWORK_IP
        #  value: "proxima1-worker"
        - name: KIND_NETWORK_IP
          value: "proxima2-worker"
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        volumeMounts:
        - name: kubeconfigs-volume
          mountPath: /etc/kubeconfigs
          readOnly: true
      serviceAccountName: edgeproxy-sa
      restartPolicy: Always
      volumes:
      - name: kubeconfigs-volume
        secret:
          secretName: kubeconfigs3
