apiVersion: v1
kind: Service
metadata:
  name: edgeproxy-service
  namespace: proxima-scheduler
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app: edgeproxy
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080