apiVersion: v1
kind: Service
metadata:
  name: edgeproxy-service
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080 
  selector:
    app: edgeproxy
