apiVersion: v1
kind: Service
metadata:
  name: edgeproxy-service
  namespace: proxima-scheduler
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: edgeproxy
