apiVersion: v1
kind: Service
metadata:
  name: edgeproxy-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 80          # The port exposed by the LoadBalancer (external port)
      targetPort: 8080   # The port on the container where the traffic will be directed
  selector:
    app: edgeproxy
