apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: admissionhandler-config
webhooks:
  - name: admissionhandler-service.proxima-scheduler.svc
    clientConfig:
      service:
        name: admissionhandler-service
        namespace: proxima-scheduler
        path: /mutate
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURIekNDQWdlZ0F3SUJBZ0lVZW1DUmJoQXJpYU5yVXdJUldSOURwTEk4OG53d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0h6RWRNQnNHQTFVRUF3d1VZV1J0YVhOemFXOXVMWGRsWW1odmIyc3RZMkV3SGhjTk1qUXhNREUzTVRneQpPREUyV2hjTk1qVXhNREUzTVRneU9ERTJXakFmTVIwd0d3WURWUVFEREJSaFpHMXBjM05wYjI0dGQyVmlhRzl2CmF5MWpZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFMRnp0bEJnbEs4Tjc3dUUKZGtkRHZ4R1FIUXBiTmIva0c2UFN6SHg1aTZHK1NBZGN1TklGaWFyYVBabWhKNTVuM3l5cnZjYytrVXFKU3ZUeQo3Zm1zWUp5bjBta2txMUgwTDZLUm5SQmJIc1BtU2VuNDVDME9uaGNYMTZTZ1JwY3ZrSDY1UHdsR0FDdjJVZW95ClpJT0NtMk9rcjZ0emJodFB5eDQ3b0pZaVpnTHo2TldjWUdtWWJJKzZHYnM4NGthUk9ST0M4bXgrR1Bxb2RRRTAKRm41MHpySEF0eW1MYmZTQnR0SE1sckw1RVZTWklQSnhCTlpWbTFYMnhydXlwM1ZUdjlueTJVblI3MmxxL1RmSApRcmNuRHhhOFJabnUvdXo5MjVQbUNLWGxFbUhmWGJSbkF1dm40ZVRwOFVleituZG42dmNrcDZtU2xJeEpkdVY1Cm5IY0tIMDhDQXdFQUFhTlRNRkV3SFFZRFZSME9CQllFRkhPdytmNzAvVndUaFNQS0dHdGhkdnJkREZmaE1COEcKQTFVZEl3UVlNQmFBRkhPdytmNzAvVndUaFNQS0dHdGhkdnJkREZmaE1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQVpsRWNrM05kUTFWcUJraUtLOVNDdFBvV0lQMXdUY01MY0ZyNXc2CmQxaUJwUExiUURsakNyM2ZScTB5Zk5rTXUxYkdHM1RiMGpmbHpNMXc5SDFTaHVpU3NaTEFvV1VXcE9JWE1NMHEKa1AwSXNhRW1ycXdIRzU2VWM0WWJJSys0c2FDSjNZRDBiTnBaK2ttOHdXWXRUL0EvMCtsNTJJZGQveEF0dXdGawoxdHVOT3cwSFZCWGZuTDVFdFJWajNYR2hnSHJvaUJEdUw0S0JIaGIrWTAzcWNxaVlsYVNvWndVZFdvWDAvSFVDCnVxK3A3dVBPT0dHVHEvOC9UR1R2TU04S1ExbVhoZ0pqL1JEeEFqL3FScWFDbzFzZFZrQkNaR2o3dGhsMDhDVTcKNU9XNi93QlVhSVZVK0RMdEFFY216Y1UyZWlQaGtPVE5VUVp4dEJkdjFHNFV5WEE9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5
    namespaceSelector:
      matchExpressions:
      - key: "kubernetes.io/metadata.name"
        operator: "NotIn"
        values:
        - "proxima-scheduler"