apiVersion: apps/v1
kind: Deployment
metadata:
  name: admissionhandler
  namespace: proxima-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admissionhandler
  template:
    metadata:
      labels:
        app: admissionhandler
    spec:
      containers:
      - name: admissionhandler
        image: bogdanb0gdan/proxima-scheduler:latest
        command: ["/admissionhandler"]
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "250m"
            memory: "128Mi"
        ports:
        - containerPort: 8080
        env:
        - name: ADMISSION_CRT_PATH
          value: "/etc/admissionhandler/certs/tls.crt"
        - name: ADMISSION_KEY_PATH
          value: "/etc/admissionhandler/certs/tls.key"
        - name: CONSUL_URL
          value: "http://consul-consul-server.consul:8500"
        volumeMounts:
        - name: admissionhandler-certs
          mountPath: /etc/admissionhandler/certs
          readOnly: true
      volumes:
      - name: admissionhandler-certs
        secret:
          secretName: admissionhandler-tls