apiVersion: v1
kind: Service
metadata:
  name: admissionhandler-service
  namespace: proxima-scheduler
spec:
  ports:
  - port: 443
    targetPort: 8080
    protocol: TCP
  selector:
    app: admissionhandler
