apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: proxima-scheduler-role
  labels:
    app: proxima-scheduler
rules:
  # list and get nodes
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list", "get"]

  # bind pods to nodes
  - apiGroups: [""]
    resources: ["pods/binding"]
    verbs: ["create"]

  # list, watch, get, update, delete pods
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "get", "watch", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: proxima-scheduler-binding
  labels:
    app: proxima-scheduler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: proxima-scheduler-role
subjects:
  - kind: ServiceAccount
    name: proxima-scheduler-sa
    namespace: proxima-scheduler
