apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: proxima-scheduler
  namespace: proxima-scheduler
  labels:
    app: proxima-scheduler
spec:
  selector:
    matchLabels:
      app: proxima-scheduler
  template:
    metadata:
      labels:
        app: proxima-scheduler
    spec:
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "edge"
        effect: "NoSchedule"
      nodeSelector:
        edge: "true"
      containers:
      - name: proxima-scheduler
        image: bogdanb0gdan/proxima-scheduler:latest
        command: ["/proxima-scheduler"]
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "250m"
            memory: "128Mi"
        env:
        - name: SCHEDULER_NAME
          value: "proxima-scheduler"
        - name: DATABASE_ENABLED
          value: "true"
        - name: SCORING_INTERVAL
          value: "10s"
        - name: EDGE_PROXIES
          # proxima1-worker, proxima2-worker inside kindinfra network
          value: "172.19.0.5,172.19.0.2"
        - name: INCLUDED_NAMESPACES
          value: "default"
        - name: INFLUXDB_ADDRESS
          # actual address of the container inside docker network
          value: "http://172.19.0.7:8086"
        - name: INFLUXDB_TOKEN
          valueFrom:
            secretKeyRef:
              name: influxdb-auth-token
              key: INFLUXDB_TOKEN
        - name: INFLUXDB_DB_SCORING
          value: "score_db"
        volumeMounts:
        - name: kubeconfigs-volume
          mountPath: /etc/kubeconfigs
          readOnly: true
      serviceAccountName: proxima-scheduler-sa
      restartPolicy: Always
      volumes:
      - name: kubeconfigs-volume
        secret:
          secretName: kubeconfigs
