apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxima-scheduler
  namespace: proxima-scheduler
  labels:
    app: proxima-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxima-scheduler
  template:
    metadata:
      labels:
        app: proxima-scheduler
    spec:
      containers:
      - name: proxima-scheduler
        image: bogdanb0gdan/proxima-scheduler:latest
        command: ["/proxima-scheduler"]
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "250m"
            memory: "128Mi"
        env:
        - name: SCHEDULER_NAME
          value: "proxima-scheduler"
        - name: DATABASE_ENABLED
          value: "true"
        - name: SCORING_INTERVAL
          value: "30s"
        - name: EDGE_PROXIES
          value: "172.104.148.76,74.207.233.55"
        - name: INCLUDED_NAMESPACES
          value: "default"
        - name: INFLUXDB_ADDRESS
          value: "http://172.104.247.42:8086"
        - name: INFLUXDB_TOKEN
          valueFrom:
            secretKeyRef:
              name: influxdb-auth-token
              key: INFLUXDB_TOKEN
        - name: INFLUXDB_DB_SCORING
          value: "score_db"
      serviceAccountName: proxima-scheduler-sa
      restartPolicy: Always
