apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-labeler-role
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-labeler-binding
subjects:
- kind: ServiceAccount
  name: labeler-sa
  namespace: proxima-scheduler
roleRef:
  kind: ClusterRole
  name: node-labeler-role
  apiGroup: rbac.authorization.k8s.io
