apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: labeler
  namespace: proxima-scheduler
  labels:
    app: labeler
spec:
  selector:
    matchLabels:
      app: labeler
  template:
    metadata:
      labels:
        app: labeler
    spec:
      serviceAccountName: labeler-sa
      containers:
      - name: labeler
        image: bogdanb0gdan/labeler:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
        - name: varlog
          mountPath: /var/log
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      tolerations:
      - key: "node-role.kubernetes.io/master"
        effect: NoSchedule