apiVersion: v1
kind: Service
metadata:
  name: chronograf-service
  namespace: influx
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  selector:
    app: chronograf
