global:
  name: proxima-us
  datacenter: dc-us
  tls:
    enabled: true

    # Here we're using the shared certificate authority from the primary
    # datacenter that was exported via the federation secret.
    caCert:
      secretName: proxima-eu-federation
      secretKey: caCert
    caKey:
      secretName: proxima-eu-federation
      secretKey: caKey

  acls:
    manageSystemACLs: false

  federation:
    enabled: true
    k8sAuthMethodHost: https://6560f7e7-41a7-4a94-b0b3-67ec72cdc5a3.cpc2-us-central-gw.linodelke.net:443
    primaryDatacenter: dc-eu
  gossipEncryption:
    secretName: proxima-eu-federation
    secretKey: gossipEncryptionKey
connectInject:
  enabled: true
meshGateway:
  enabled: true
server:
  # Here we're including the server config exported from the primary
  # via the federation secret. This config includes the addresses of
  # the primary datacenter's mesh gateways so Consul can begin federation.
  extraVolumes:
    - type: secret
      name: proxima-eu-federation
      items:
        - key: serverConfigJSON
          path: config.json
      load: true
