apiVersion: apps/v1
kind: Deployment
metadata:
  name: chronograf
  namespace: influx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chronograf
  template:
    metadata:
      labels:
        app: chronograf
    spec:
      containers:
      - name: chronograf
        image: chronograf:latest
        ports:
        - containerPort: 8888