apiVersion: v1
kind: Service
metadata:
  name: chronograf
  namespace: influx
spec:
  type: NodePort
  ports:
    - port: 8888
      nodePort: 32001
      protocol: TCP
  selector:
    app: chronograf
