apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  namespace: influx
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
  selector:
    app: influxdb
