apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-flask-service-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-flask-service
  template:
    metadata:
      labels:
        app: test-flask-service
      annotations:
        consul-register: "true"
    spec:
      containers:
      - name: test-flask-service-container
        image: bogdanb0gdan/test-flask-service:latest
        ports:
        - containerPort: 8080

