apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pinger-role
  labels:
    app: pinger
rules:
  # list and get nodes
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pinger-binding
  labels:
    app: pinger
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pinger-role
subjects:
  - kind: ServiceAccount
    name: pinger-sa
    namespace: proxima-scheduler