apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pinger
  namespace: proxima-scheduler
  labels:
    app: pinger
spec:
  selector:
    matchLabels:
      app: pinger
  template:
    metadata:
      labels:
        app: pinger
    spec:
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "edge"
        effect: "NoSchedule"
      nodeSelector:
        edge: "true"
      containers:
      - name: pinger
        image: bogdanb0gdan/proxima-scheduler:latest
        command: ["/pinger"]
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "250m"
            memory: "128Mi"
        env:
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        # used on Kind cluster locally,
        # the ip of the Node, needed for edgeproxy + pinger
        - name: KIND_NETWORK_IP
          value: "172.19.0.2"
        #- name: KIND_NETWORK_IP
        #  value: "172.19.0.5"
        - name: DATABASE_ENABLED
          value: "true"
        - name: PING_INTERVAL
          value: "10s"
        - name: INCLUDED_NAMESPACES
          value: "default"
        - name: INFLUXDB_ADDRESS
          # actual address of the container inside docker network
          value: "http://172.19.0.7:8086"
        - name: INFLUXDB_TOKEN
          valueFrom:
            secretKeyRef:
              name: influxdb-auth-token
              key: INFLUXDB_TOKEN
        #- name: EDGE_PROXIES
        #  value: "172.104.148.76,74.207.233.55"
        - name: EDGE_PROXIES
          # proxima1-worker, proxima2-worker inside kindinfra network
          value: "172.19.0.5,172.19.0.2"
      serviceAccountName: pinger-sa
      restartPolicy: Always