apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pinger
  namespace: proxima-scheduler
  labels:
    app: pinger
spec:
  selector:
    matchLabels:
      app: pinger
  template:
    metadata:
      labels:
        app: pinger
    spec:
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "edge"
        effect: "NoSchedule"
      nodeSelector:
        edge: "true"
      containers:
      - name: pinger
        image: bogdanb0gdan/proxima-scheduler:latest
        command: ["/pinger"]
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "250m"
            memory: "128Mi"
        env:
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DATABASE_ENABLED
          value: "true"
        - name: PING_INTERVAL
          value: "10s"
        - name: INCLUDED_NAMESPACES
          value: "default"
        - name: INFLUXDB_ADDRESS
          value: "http://172.104.247.42:8086"
        - name: INFLUXDB_TOKEN
          valueFrom:
            secretKeyRef:
              name: influxdb-auth-token
              key: INFLUXDB_TOKEN
      serviceAccountName: pinger-sa
      restartPolicy: Always