name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-proxima-scheduler:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and Push Proxima Scheduler Docker Image
      uses: docker/build-push-action@v4
      with:
        context: ./proxima-scheduler
        file: ./proxima-scheduler/Dockerfile
        push: true
        tags: |
          bogdanb0gdan/proxima-scheduler:latest
          bogdanb0gdan/proxima-scheduler:${{ github.sha }}

    - name: Docker Image Digest
      run: echo ${{ steps.build.outputs.digest }}

  build-labeler:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and Push Labeler Docker Image
      uses: docker/build-push-action@v4
      with:
        context: ./proxima-scheduler/labeler
        file: ./proxima-scheduler/labeler/Dockerfile
        push: true
        tags: |
          bogdanb0gdan/labeler:latest
          bogdanb0gdan/labeler:${{ github.sha }}

    - name: Docker Image Digest
      run: echo ${{ steps.build.outputs.digest }}
